#!/usr/bin/env node
// Vendors the silverballmania design tokens into the overlay as a CSS string.
// Source of truth: ~/Repositories/design-systems/silverballmania/ (see
// .claude/design-system.json). Re-run after bumping the pinned version.
//
// Transformations (design-system gaps G1–G3):
//   - :root → :host and [data-theme="light"] → :host([data-theme="light"]) so the
//     tokens apply inside the overlay's shadow root
//   - the Google Fonts @import and the Montserrat @font-face are removed; the
//     font stacks keep their system fallbacks
//   - the broadcast token block (section 7b) is dropped; the overlay is not video
import { readFileSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import path from 'node:path'

const SLUG = 'silverballmania'
const canon = path.join(homedir(), 'Repositories/design-systems', SLUG)
const manifest = JSON.parse(readFileSync(path.join(canon, 'manifest.json'), 'utf8'))
let css = readFileSync(path.join(canon, 'tokens.css'), 'utf8')

const before = css.length
css = css.replace(/^@import url\([^\n]*\n/m, '')
css = css.replace(/^@font-face \{[^\n]*\n/m, '')

// Drop section 7b (broadcast) up to the light-theme header.
const bcStart = css.indexOf('   * 7b. BROADCAST')
const lightHeader = css.indexOf(
  '/* ============================================================================\n * 8. LIGHT THEME',
)
if (bcStart === -1 || lightHeader === -1)
  throw new Error('vendor-tokens: section markers not found; canon layout changed')
const sectionStart = css.lastIndexOf('  /* ==', bcStart)
css = css.slice(0, sectionStart) + '}\n\n' + css.slice(lightHeader)

const replacements = [
  [':root,\n[data-theme="light"] .hero-dark,\n.light .hero-dark {', ':host {'],
  ['[data-theme="light"],\n.light {', ':host([data-theme="light"]),\n:host(.light) {'],
  ['[data-theme="light"] .hero-dark,\n.light .hero-dark { /* palette: see :root */ }\n', ''],
  [
    '@media (prefers-reduced-motion: reduce) {\n  :root {',
    '@media (prefers-reduced-motion: reduce) {\n  :host {',
  ],
]
for (const [from, to] of replacements) {
  if (!css.includes(from))
    throw new Error(`vendor-tokens: expected fragment missing: ${from.slice(0, 40)}…`)
  css = css.replace(from, to)
}
// Comments are the bulk of the canon file and document the values; the canon
// stays the reference, so the vendored copy ships without them.
css =
  css
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/[ \t]+$/gm, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim() + '\n'
if (/(^|[\s,]):root\b/.test(css) || /\[data-theme="light"\] \./.test(css))
  throw new Error('vendor-tokens: untransformed selector left')

const header = `// GENERATED by scripts/vendor-tokens.mjs — do not edit.
// SOURCE: design-systems/${SLUG} v${manifest.version} (${manifest.source.at(-1).date}), tokens.css
// Vendored ${new Date().toISOString().slice(0, 10)}; :root→:host, fonts and broadcast section stripped.
`
writeFileSync(
  path.join(process.cwd(), 'src/overlay/tokens.generated.ts'),
  header + 'export const tokensCss = ' + JSON.stringify(css) + '\n',
)
console.log(`vendored ${SLUG} v${manifest.version}: ${before} → ${css.length} chars`)
